---
- hosts: server1
  tasks:
  - name: remove existing repository
    shell: rm -rf 2020_03_DO_Boston_casestudy_part_1
    
  - name: pull repository
    shell: git clone https://github.com/hakanco/2020_03_DO_Boston_casestudy_part_1.git
  
  - name: deploy flask app
    shell: kubectl apply -f  ~/2020_03_DO_Boston_casestudy_part_1/kubernetes.yaml
  
  - name: scale up to 5 replicas
    shell: kubectl scale deployment/capstone-part1-deployment --replicas=5
