
---
- hosts: server1
  tasks:
  - name: Update system
    shell: |
     sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get upgrade
    
 # - name: install virtualbox
 #  shell: sudo apt install -y virtualbox virtualbox-ext-pack
    
  - name: download minikube binary & put the binary under /usr/local/bin directory 
    shell: wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
           && chmod +x minikube-linux-amd64 && sudo mv minikube-linux-amd64 /usr/local/bin/minikube
           
  - name: install kubectl on ubuntu
    shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    
  - name: make the kubectl binary executable
    shell: chmod +x ./kubectl
    
  - name: move the binary into its PATH
    shell: sudo mv ./kubectl /usr/local/bin/kubectl
    
  - name: start kubernetes cluster
    shell: minikube start
    register: output
    
  - name: remove existing repository
    shell: rm -rf 2020_03_DO_Boston_casestudy_part_1
    
  - name: pull repository
    shell: git clone https://github.com/hakanco/2020_03_DO_Boston_casestudy_part_1.git
  
  - name: deploy flask app
    shell: kubectl apply -f ~/2020_03_DO_Boston_casestudy_part_1/kubernetes.yaml
