apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: capstone-part1-deployment
spec:
  selector:
    matchLabels:
      app: capstone-part1
  replicas: 3 
  template:
    metadata:
      labels:
        app: capstone-part1
    spec:
      containers:
      - name: capstone-part1-container 
        image: buildapp/capstone-part1
        ports:
        - containerPort: 9090
---

apiVersion: v1
kind: Service
metadata:
  name: capstone-part1-service
spec:
  type: NodePort
  selector:
    app: capstone-part1
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32000
